[project]
name = "order-service"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
dev = [
    "pytest>=9.0.3",
]

[[tool.uv.index]]
name = "graftcode"
url = "https://grft.dev/simple/36b7015b-2889-4c56-9e2f-9555e73bfdf2__free"
explicit = true

[tool.uv.sources]
graft-pypi-pricing-service-graft = { index = "graftcode" }

[tool.pytest.ini_options]
testpaths = ["tests"]
